backend:
  name: git-gateway
  branch: main
site_url: https://gotexshow.com.br/
media_folder: 'static/uploads/noticias'
public_folder: '/uploads/noticias'
locale: 'pt-br'

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: noticias
    label: Notícias
    label_singular: Notícia
    folder: content/pt-br/noticias
    create: true
    editor:
      preview: false
    slug: '{{slug}}'
    fields:
      - { label: 'Título do post', name: 'title', widget: 'string', hint: 'Recomendação: Entre 40 a 90 caractéres.', required: true }
      - { label: 'Descrição', name: 'description', widget: 'string', hint: 'Resumo do post. Aparecerá no índice, feed e também como meta-descrição. Recomendação: Entre 90 a 140 caractéres.', required: true }
      - { label: 'Permalink', name: 'slug', widget: 'string', hint: 'URL da página. Utilize hífen no lugar de espaços e SUBSTITUA caractéres especiais. Ex: divulgacao-da-minha-noticia.', required: true }
      - { label: "Categorias", name: "categories", widget: "select", multiple: true, min: 1, max: 2, options: ["Artigos", "Destaques", "Evento", "Mercado"], default: ["Artigos"], hint: 'Selecione até duas categorias.', required: true }
      - { label: 'Tipo de conteúdo', name: 'type', widget: 'hidden', default: "pages/noticias" }
      - { label: 'Imagem', name: 'image', widget: 'image', hint: 'Recomendação de tamanho: 1010x630 pixels.' }
      - { label: 'Data de publicação', name: 'date', widget: 'date', required: true }
      - { label: 'Rascunho', name: 'draft', widget: 'boolean', hint: 'Caso deseje manter o post como rascunho, ative a opção acima.', default: false }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown', required: true }